from __future__ import annotations

from typing import Protocol

from app.domain.entities import Book


class BookRepository(Protocol):
    def add(self, book: Book) -> Book: ...
    def get(self, book_id: int) -> Book | None: ...
    def update(self, book: Book) -> Book: ...
    def search(self, query: str | None, limit: int, offset: int) -> list[Book]: ...
    def lock_for_update(self, book_id: int) -> Book | None: ...
    def increment_active_loans(self, book_id: int) -> None: ...
    def decrement_active_loans(self, book_id: int) -> None: ...
