from __future__ import annotations

from datetime import datetime
from typing import Protocol

from app.domain.entities import Loan


class LoanRepository(Protocol):
    def add(self, loan: Loan) -> Loan: ...
    def get(self, loan_id: int) -> Loan | None: ...
    def update(self, loan: Loan) -> Loan: ...
    def mark_returned(self, loan_id: int, returned_at: datetime) -> Loan | None: ...
    def count_active_for_book(self, book_id: int) -> int: ...
    def count_active_for_books(self, book_ids: list[int]) -> dict[int, int]: ...
    def find_active_by_book_and_member(self, book_id: int, member_id: int) -> Loan | None: ...
    def list_active_by_member(self, member_id: int) -> list[Loan]: ...
    def list(
        self,
        *,
        member_id: int | None,
        book_id: int | None,
        active_only: bool,
        limit: int,
        offset: int,
    ) -> list[Loan]: ...
