from __future__ import annotations

from typing import Protocol

from app.domain.entities import Member


class MemberRepository(Protocol):
    def add(self, member: Member) -> Member: ...
    def get(self, member_id: int) -> Member | None: ...
    def get_by_email(self, email: str) -> Member | None: ...
    def update(self, member: Member) -> Member: ...
    def list(self, limit: int, offset: int) -> list[Member]: ...
