// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v6.31.1
// source: book.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Pagination } from "./common";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "library.book";

export interface Book {
  id: number;
  title: string;
  author: string;
  isbn: string;
  totalCopies: number;
  availableCopies: number;
  createdAt: Date | undefined;
  updatedAt: Date | undefined;
}

export interface CreateBookRequest {
  title: string;
  author: string;
  isbn: string;
  totalCopies: number;
}

export interface UpdateBookRequest {
  id: number;
  title: string;
  author: string;
  isbn: string;
  totalCopies: number;
}

export interface GetBookRequest {
  id: number;
}

export interface SearchBooksRequest {
  query: string;
  pagination: Pagination | undefined;
}

export interface SearchBooksResponse {
  books: Book[];
}

function createBaseBook(): Book {
  return {
    id: 0,
    title: "",
    author: "",
    isbn: "",
    totalCopies: 0,
    availableCopies: 0,
    createdAt: undefined,
    updatedAt: undefined,
  };
}

export const Book: MessageFns<Book> = {
  encode(message: Book, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(34).string(message.isbn);
    }
    if (message.totalCopies !== 0) {
      writer.uint32(40).int32(message.totalCopies);
    }
    if (message.availableCopies !== 0) {
      writer.uint32(48).int32(message.availableCopies);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(58).fork()).join();
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.updatedAt), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Book {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBook();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalCopies = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.availableCopies = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Book {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      totalCopies: isSet(object.totalCopies) ? globalThis.Number(object.totalCopies) : 0,
      availableCopies: isSet(object.availableCopies) ? globalThis.Number(object.availableCopies) : 0,
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      updatedAt: isSet(object.updatedAt) ? fromJsonTimestamp(object.updatedAt) : undefined,
    };
  },

  toJSON(message: Book): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.totalCopies !== 0) {
      obj.totalCopies = Math.round(message.totalCopies);
    }
    if (message.availableCopies !== 0) {
      obj.availableCopies = Math.round(message.availableCopies);
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.updatedAt !== undefined) {
      obj.updatedAt = message.updatedAt.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<Book>): Book {
    return Book.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Book>): Book {
    const message = createBaseBook();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.totalCopies = object.totalCopies ?? 0;
    message.availableCopies = object.availableCopies ?? 0;
    message.createdAt = object.createdAt ?? undefined;
    message.updatedAt = object.updatedAt ?? undefined;
    return message;
  },
};

function createBaseCreateBookRequest(): CreateBookRequest {
  return { title: "", author: "", isbn: "", totalCopies: 0 };
}

export const CreateBookRequest: MessageFns<CreateBookRequest> = {
  encode(message: CreateBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(18).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(26).string(message.isbn);
    }
    if (message.totalCopies !== 0) {
      writer.uint32(32).int32(message.totalCopies);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalCopies = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateBookRequest {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      totalCopies: isSet(object.totalCopies) ? globalThis.Number(object.totalCopies) : 0,
    };
  },

  toJSON(message: CreateBookRequest): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.totalCopies !== 0) {
      obj.totalCopies = Math.round(message.totalCopies);
    }
    return obj;
  },

  create(base?: DeepPartial<CreateBookRequest>): CreateBookRequest {
    return CreateBookRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CreateBookRequest>): CreateBookRequest {
    const message = createBaseCreateBookRequest();
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.totalCopies = object.totalCopies ?? 0;
    return message;
  },
};

function createBaseUpdateBookRequest(): UpdateBookRequest {
  return { id: 0, title: "", author: "", isbn: "", totalCopies: 0 };
}

export const UpdateBookRequest: MessageFns<UpdateBookRequest> = {
  encode(message: UpdateBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.author !== "") {
      writer.uint32(26).string(message.author);
    }
    if (message.isbn !== "") {
      writer.uint32(34).string(message.isbn);
    }
    if (message.totalCopies !== 0) {
      writer.uint32(40).int32(message.totalCopies);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.author = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.isbn = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.totalCopies = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateBookRequest {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      author: isSet(object.author) ? globalThis.String(object.author) : "",
      isbn: isSet(object.isbn) ? globalThis.String(object.isbn) : "",
      totalCopies: isSet(object.totalCopies) ? globalThis.Number(object.totalCopies) : 0,
    };
  },

  toJSON(message: UpdateBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.author !== "") {
      obj.author = message.author;
    }
    if (message.isbn !== "") {
      obj.isbn = message.isbn;
    }
    if (message.totalCopies !== 0) {
      obj.totalCopies = Math.round(message.totalCopies);
    }
    return obj;
  },

  create(base?: DeepPartial<UpdateBookRequest>): UpdateBookRequest {
    return UpdateBookRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<UpdateBookRequest>): UpdateBookRequest {
    const message = createBaseUpdateBookRequest();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.author = object.author ?? "";
    message.isbn = object.isbn ?? "";
    message.totalCopies = object.totalCopies ?? 0;
    return message;
  },
};

function createBaseGetBookRequest(): GetBookRequest {
  return { id: 0 };
}

export const GetBookRequest: MessageFns<GetBookRequest> = {
  encode(message: GetBookRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetBookRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetBookRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetBookRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetBookRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create(base?: DeepPartial<GetBookRequest>): GetBookRequest {
    return GetBookRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetBookRequest>): GetBookRequest {
    const message = createBaseGetBookRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseSearchBooksRequest(): SearchBooksRequest {
  return { query: "", pagination: undefined };
}

export const SearchBooksRequest: MessageFns<SearchBooksRequest> = {
  encode(message: SearchBooksRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.pagination !== undefined) {
      Pagination.encode(message.pagination, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchBooksRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchBooksRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pagination = Pagination.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchBooksRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      pagination: isSet(object.pagination) ? Pagination.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: SearchBooksRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.pagination !== undefined) {
      obj.pagination = Pagination.toJSON(message.pagination);
    }
    return obj;
  },

  create(base?: DeepPartial<SearchBooksRequest>): SearchBooksRequest {
    return SearchBooksRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchBooksRequest>): SearchBooksRequest {
    const message = createBaseSearchBooksRequest();
    message.query = object.query ?? "";
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? Pagination.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseSearchBooksResponse(): SearchBooksResponse {
  return { books: [] };
}

export const SearchBooksResponse: MessageFns<SearchBooksResponse> = {
  encode(message: SearchBooksResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.books) {
      Book.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SearchBooksResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchBooksResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.books.push(Book.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchBooksResponse {
    return { books: globalThis.Array.isArray(object?.books) ? object.books.map((e: any) => Book.fromJSON(e)) : [] };
  },

  toJSON(message: SearchBooksResponse): unknown {
    const obj: any = {};
    if (message.books?.length) {
      obj.books = message.books.map((e) => Book.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<SearchBooksResponse>): SearchBooksResponse {
    return SearchBooksResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SearchBooksResponse>): SearchBooksResponse {
    const message = createBaseSearchBooksResponse();
    message.books = object.books?.map((e) => Book.fromPartial(e)) || [];
    return message;
  },
};

export interface BookService {
  CreateBook(request: DeepPartial<CreateBookRequest>, metadata?: grpc.Metadata): Promise<Book>;
  UpdateBook(request: DeepPartial<UpdateBookRequest>, metadata?: grpc.Metadata): Promise<Book>;
  GetBook(request: DeepPartial<GetBookRequest>, metadata?: grpc.Metadata): Promise<Book>;
  SearchBooks(request: DeepPartial<SearchBooksRequest>, metadata?: grpc.Metadata): Promise<SearchBooksResponse>;
}

export class BookServiceClientImpl implements BookService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.CreateBook = this.CreateBook.bind(this);
    this.UpdateBook = this.UpdateBook.bind(this);
    this.GetBook = this.GetBook.bind(this);
    this.SearchBooks = this.SearchBooks.bind(this);
  }

  CreateBook(request: DeepPartial<CreateBookRequest>, metadata?: grpc.Metadata): Promise<Book> {
    return this.rpc.unary(BookServiceCreateBookDesc, CreateBookRequest.fromPartial(request), metadata);
  }

  UpdateBook(request: DeepPartial<UpdateBookRequest>, metadata?: grpc.Metadata): Promise<Book> {
    return this.rpc.unary(BookServiceUpdateBookDesc, UpdateBookRequest.fromPartial(request), metadata);
  }

  GetBook(request: DeepPartial<GetBookRequest>, metadata?: grpc.Metadata): Promise<Book> {
    return this.rpc.unary(BookServiceGetBookDesc, GetBookRequest.fromPartial(request), metadata);
  }

  SearchBooks(request: DeepPartial<SearchBooksRequest>, metadata?: grpc.Metadata): Promise<SearchBooksResponse> {
    return this.rpc.unary(BookServiceSearchBooksDesc, SearchBooksRequest.fromPartial(request), metadata);
  }
}

export const BookServiceDesc = { serviceName: "library.book.BookService" };

export const BookServiceCreateBookDesc: UnaryMethodDefinitionish = {
  methodName: "CreateBook",
  service: BookServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return CreateBookRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Book.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const BookServiceUpdateBookDesc: UnaryMethodDefinitionish = {
  methodName: "UpdateBook",
  service: BookServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return UpdateBookRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Book.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const BookServiceGetBookDesc: UnaryMethodDefinitionish = {
  methodName: "GetBook",
  service: BookServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return GetBookRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Book.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const BookServiceSearchBooksDesc: UnaryMethodDefinitionish = {
  methodName: "SearchBooks",
  service: BookServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return SearchBooksRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = SearchBooksResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
