// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.5
//   protoc               v6.31.1
// source: loan.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { grpc } from "@improbable-eng/grpc-web";
import { BrowserHeaders } from "browser-headers";
import { Pagination } from "./common";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "library.loan";

export interface Loan {
  id: number;
  bookId: number;
  memberId: number;
  borrowedAt: Date | undefined;
  dueAt: Date | undefined;
  returnedAt: Date | undefined;
  isOverdue: boolean;
}

export interface BorrowRequest {
  bookId: number;
  memberId: number;
  days: number;
}

export interface ReturnLoanRequest {
  loanId: number;
}

export interface ListLoansRequest {
  memberId: number;
  bookId: number;
  activeOnly: boolean;
  pagination: Pagination | undefined;
}

export interface ListLoansByMemberRequest {
  memberId: number;
}

export interface ListLoansResponse {
  loans: Loan[];
}

function createBaseLoan(): Loan {
  return {
    id: 0,
    bookId: 0,
    memberId: 0,
    borrowedAt: undefined,
    dueAt: undefined,
    returnedAt: undefined,
    isOverdue: false,
  };
}

export const Loan: MessageFns<Loan> = {
  encode(message: Loan, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.bookId !== 0) {
      writer.uint32(16).int64(message.bookId);
    }
    if (message.memberId !== 0) {
      writer.uint32(24).int64(message.memberId);
    }
    if (message.borrowedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.borrowedAt), writer.uint32(34).fork()).join();
    }
    if (message.dueAt !== undefined) {
      Timestamp.encode(toTimestamp(message.dueAt), writer.uint32(42).fork()).join();
    }
    if (message.returnedAt !== undefined) {
      Timestamp.encode(toTimestamp(message.returnedAt), writer.uint32(50).fork()).join();
    }
    if (message.isOverdue !== false) {
      writer.uint32(56).bool(message.isOverdue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Loan {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoan();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.memberId = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.borrowedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.dueAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.returnedAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isOverdue = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Loan {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      bookId: isSet(object.bookId) ? globalThis.Number(object.bookId) : 0,
      memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0,
      borrowedAt: isSet(object.borrowedAt) ? fromJsonTimestamp(object.borrowedAt) : undefined,
      dueAt: isSet(object.dueAt) ? fromJsonTimestamp(object.dueAt) : undefined,
      returnedAt: isSet(object.returnedAt) ? fromJsonTimestamp(object.returnedAt) : undefined,
      isOverdue: isSet(object.isOverdue) ? globalThis.Boolean(object.isOverdue) : false,
    };
  },

  toJSON(message: Loan): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.bookId !== 0) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.borrowedAt !== undefined) {
      obj.borrowedAt = message.borrowedAt.toISOString();
    }
    if (message.dueAt !== undefined) {
      obj.dueAt = message.dueAt.toISOString();
    }
    if (message.returnedAt !== undefined) {
      obj.returnedAt = message.returnedAt.toISOString();
    }
    if (message.isOverdue !== false) {
      obj.isOverdue = message.isOverdue;
    }
    return obj;
  },

  create(base?: DeepPartial<Loan>): Loan {
    return Loan.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Loan>): Loan {
    const message = createBaseLoan();
    message.id = object.id ?? 0;
    message.bookId = object.bookId ?? 0;
    message.memberId = object.memberId ?? 0;
    message.borrowedAt = object.borrowedAt ?? undefined;
    message.dueAt = object.dueAt ?? undefined;
    message.returnedAt = object.returnedAt ?? undefined;
    message.isOverdue = object.isOverdue ?? false;
    return message;
  },
};

function createBaseBorrowRequest(): BorrowRequest {
  return { bookId: 0, memberId: 0, days: 0 };
}

export const BorrowRequest: MessageFns<BorrowRequest> = {
  encode(message: BorrowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.bookId !== 0) {
      writer.uint32(8).int64(message.bookId);
    }
    if (message.memberId !== 0) {
      writer.uint32(16).int64(message.memberId);
    }
    if (message.days !== 0) {
      writer.uint32(24).int32(message.days);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BorrowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBorrowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.bookId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.memberId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.days = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BorrowRequest {
    return {
      bookId: isSet(object.bookId) ? globalThis.Number(object.bookId) : 0,
      memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0,
      days: isSet(object.days) ? globalThis.Number(object.days) : 0,
    };
  },

  toJSON(message: BorrowRequest): unknown {
    const obj: any = {};
    if (message.bookId !== 0) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.days !== 0) {
      obj.days = Math.round(message.days);
    }
    return obj;
  },

  create(base?: DeepPartial<BorrowRequest>): BorrowRequest {
    return BorrowRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<BorrowRequest>): BorrowRequest {
    const message = createBaseBorrowRequest();
    message.bookId = object.bookId ?? 0;
    message.memberId = object.memberId ?? 0;
    message.days = object.days ?? 0;
    return message;
  },
};

function createBaseReturnLoanRequest(): ReturnLoanRequest {
  return { loanId: 0 };
}

export const ReturnLoanRequest: MessageFns<ReturnLoanRequest> = {
  encode(message: ReturnLoanRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.loanId !== 0) {
      writer.uint32(8).int64(message.loanId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReturnLoanRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReturnLoanRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.loanId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReturnLoanRequest {
    return { loanId: isSet(object.loanId) ? globalThis.Number(object.loanId) : 0 };
  },

  toJSON(message: ReturnLoanRequest): unknown {
    const obj: any = {};
    if (message.loanId !== 0) {
      obj.loanId = Math.round(message.loanId);
    }
    return obj;
  },

  create(base?: DeepPartial<ReturnLoanRequest>): ReturnLoanRequest {
    return ReturnLoanRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ReturnLoanRequest>): ReturnLoanRequest {
    const message = createBaseReturnLoanRequest();
    message.loanId = object.loanId ?? 0;
    return message;
  },
};

function createBaseListLoansRequest(): ListLoansRequest {
  return { memberId: 0, bookId: 0, activeOnly: false, pagination: undefined };
}

export const ListLoansRequest: MessageFns<ListLoansRequest> = {
  encode(message: ListLoansRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== 0) {
      writer.uint32(8).int64(message.memberId);
    }
    if (message.bookId !== 0) {
      writer.uint32(16).int64(message.bookId);
    }
    if (message.activeOnly !== false) {
      writer.uint32(24).bool(message.activeOnly);
    }
    if (message.pagination !== undefined) {
      Pagination.encode(message.pagination, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLoansRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLoansRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.memberId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.activeOnly = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pagination = Pagination.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLoansRequest {
    return {
      memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0,
      bookId: isSet(object.bookId) ? globalThis.Number(object.bookId) : 0,
      activeOnly: isSet(object.activeOnly) ? globalThis.Boolean(object.activeOnly) : false,
      pagination: isSet(object.pagination) ? Pagination.fromJSON(object.pagination) : undefined,
    };
  },

  toJSON(message: ListLoansRequest): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    if (message.bookId !== 0) {
      obj.bookId = Math.round(message.bookId);
    }
    if (message.activeOnly !== false) {
      obj.activeOnly = message.activeOnly;
    }
    if (message.pagination !== undefined) {
      obj.pagination = Pagination.toJSON(message.pagination);
    }
    return obj;
  },

  create(base?: DeepPartial<ListLoansRequest>): ListLoansRequest {
    return ListLoansRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListLoansRequest>): ListLoansRequest {
    const message = createBaseListLoansRequest();
    message.memberId = object.memberId ?? 0;
    message.bookId = object.bookId ?? 0;
    message.activeOnly = object.activeOnly ?? false;
    message.pagination = (object.pagination !== undefined && object.pagination !== null)
      ? Pagination.fromPartial(object.pagination)
      : undefined;
    return message;
  },
};

function createBaseListLoansByMemberRequest(): ListLoansByMemberRequest {
  return { memberId: 0 };
}

export const ListLoansByMemberRequest: MessageFns<ListLoansByMemberRequest> = {
  encode(message: ListLoansByMemberRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== 0) {
      writer.uint32(8).int64(message.memberId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLoansByMemberRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLoansByMemberRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.memberId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLoansByMemberRequest {
    return { memberId: isSet(object.memberId) ? globalThis.Number(object.memberId) : 0 };
  },

  toJSON(message: ListLoansByMemberRequest): unknown {
    const obj: any = {};
    if (message.memberId !== 0) {
      obj.memberId = Math.round(message.memberId);
    }
    return obj;
  },

  create(base?: DeepPartial<ListLoansByMemberRequest>): ListLoansByMemberRequest {
    return ListLoansByMemberRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListLoansByMemberRequest>): ListLoansByMemberRequest {
    const message = createBaseListLoansByMemberRequest();
    message.memberId = object.memberId ?? 0;
    return message;
  },
};

function createBaseListLoansResponse(): ListLoansResponse {
  return { loans: [] };
}

export const ListLoansResponse: MessageFns<ListLoansResponse> = {
  encode(message: ListLoansResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.loans) {
      Loan.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListLoansResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListLoansResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.loans.push(Loan.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListLoansResponse {
    return { loans: globalThis.Array.isArray(object?.loans) ? object.loans.map((e: any) => Loan.fromJSON(e)) : [] };
  },

  toJSON(message: ListLoansResponse): unknown {
    const obj: any = {};
    if (message.loans?.length) {
      obj.loans = message.loans.map((e) => Loan.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<ListLoansResponse>): ListLoansResponse {
    return ListLoansResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ListLoansResponse>): ListLoansResponse {
    const message = createBaseListLoansResponse();
    message.loans = object.loans?.map((e) => Loan.fromPartial(e)) || [];
    return message;
  },
};

export interface LoanService {
  Borrow(request: DeepPartial<BorrowRequest>, metadata?: grpc.Metadata): Promise<Loan>;
  ReturnLoan(request: DeepPartial<ReturnLoanRequest>, metadata?: grpc.Metadata): Promise<Loan>;
  ListLoans(request: DeepPartial<ListLoansRequest>, metadata?: grpc.Metadata): Promise<ListLoansResponse>;
  ListLoansByMember(
    request: DeepPartial<ListLoansByMemberRequest>,
    metadata?: grpc.Metadata,
  ): Promise<ListLoansResponse>;
}

export class LoanServiceClientImpl implements LoanService {
  private readonly rpc: Rpc;

  constructor(rpc: Rpc) {
    this.rpc = rpc;
    this.Borrow = this.Borrow.bind(this);
    this.ReturnLoan = this.ReturnLoan.bind(this);
    this.ListLoans = this.ListLoans.bind(this);
    this.ListLoansByMember = this.ListLoansByMember.bind(this);
  }

  Borrow(request: DeepPartial<BorrowRequest>, metadata?: grpc.Metadata): Promise<Loan> {
    return this.rpc.unary(LoanServiceBorrowDesc, BorrowRequest.fromPartial(request), metadata);
  }

  ReturnLoan(request: DeepPartial<ReturnLoanRequest>, metadata?: grpc.Metadata): Promise<Loan> {
    return this.rpc.unary(LoanServiceReturnLoanDesc, ReturnLoanRequest.fromPartial(request), metadata);
  }

  ListLoans(request: DeepPartial<ListLoansRequest>, metadata?: grpc.Metadata): Promise<ListLoansResponse> {
    return this.rpc.unary(LoanServiceListLoansDesc, ListLoansRequest.fromPartial(request), metadata);
  }

  ListLoansByMember(
    request: DeepPartial<ListLoansByMemberRequest>,
    metadata?: grpc.Metadata,
  ): Promise<ListLoansResponse> {
    return this.rpc.unary(LoanServiceListLoansByMemberDesc, ListLoansByMemberRequest.fromPartial(request), metadata);
  }
}

export const LoanServiceDesc = { serviceName: "library.loan.LoanService" };

export const LoanServiceBorrowDesc: UnaryMethodDefinitionish = {
  methodName: "Borrow",
  service: LoanServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return BorrowRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Loan.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const LoanServiceReturnLoanDesc: UnaryMethodDefinitionish = {
  methodName: "ReturnLoan",
  service: LoanServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return ReturnLoanRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = Loan.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const LoanServiceListLoansDesc: UnaryMethodDefinitionish = {
  methodName: "ListLoans",
  service: LoanServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return ListLoansRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = ListLoansResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

export const LoanServiceListLoansByMemberDesc: UnaryMethodDefinitionish = {
  methodName: "ListLoansByMember",
  service: LoanServiceDesc,
  requestStream: false,
  responseStream: false,
  requestType: {
    serializeBinary() {
      return ListLoansByMemberRequest.encode(this).finish();
    },
  } as any,
  responseType: {
    deserializeBinary(data: Uint8Array) {
      const value = ListLoansResponse.decode(data);
      return {
        ...value,
        toObject() {
          return value;
        },
      };
    },
  } as any,
};

interface UnaryMethodDefinitionishR extends grpc.UnaryMethodDefinition<any, any> {
  requestStream: any;
  responseStream: any;
}

type UnaryMethodDefinitionish = UnaryMethodDefinitionishR;

interface Rpc {
  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any>;
}

export class GrpcWebImpl {
  private host: string;
  private options: {
    transport?: grpc.TransportFactory;

    debug?: boolean;
    metadata?: grpc.Metadata;
    upStreamRetryCodes?: number[];
  };

  constructor(
    host: string,
    options: {
      transport?: grpc.TransportFactory;

      debug?: boolean;
      metadata?: grpc.Metadata;
      upStreamRetryCodes?: number[];
    },
  ) {
    this.host = host;
    this.options = options;
  }

  unary<T extends UnaryMethodDefinitionish>(
    methodDesc: T,
    _request: any,
    metadata: grpc.Metadata | undefined,
  ): Promise<any> {
    const request = { ..._request, ...methodDesc.requestType };
    const maybeCombinedMetadata = metadata && this.options.metadata
      ? new BrowserHeaders({ ...this.options?.metadata.headersMap, ...metadata?.headersMap })
      : metadata ?? this.options.metadata;
    return new Promise((resolve, reject) => {
      grpc.unary(methodDesc, {
        request,
        host: this.host,
        metadata: maybeCombinedMetadata ?? {},
        ...(this.options.transport !== undefined ? { transport: this.options.transport } : {}),
        debug: this.options.debug ?? false,
        onEnd: function (response) {
          if (response.status === grpc.Code.OK) {
            resolve(response.message!.toObject());
          } else {
            const err = new GrpcWebError(response.statusMessage, response.status, response.trailers);
            reject(err);
          }
        },
      });
    });
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export class GrpcWebError extends globalThis.Error {
  constructor(message: string, public code: grpc.Code, public metadata: grpc.Metadata) {
    super(message);
  }
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
