# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x0clibrary.book\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xcf\x01\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\x14\n\x0ctotal_copies\x18\x05 \x01(\x05\x12\x18\n\x10\x61vailable_copies\x18\x06 \x01(\x05\x12.\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"V\n\x11\x43reateBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x14\n\x0ctotal_copies\x18\x04 \x01(\x05\"b\n\x11UpdateBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x0c\n\x04isbn\x18\x04 \x01(\t\x12\x14\n\x0ctotal_copies\x18\x05 \x01(\x05\"\x1c\n\x0eGetBookRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"S\n\x12SearchBooksRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12.\n\npagination\x18\x02 \x01(\x0b\x32\x1a.library.common.Pagination\"8\n\x13SearchBooksResponse\x12!\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x12.library.book.Book2\xa4\x02\n\x0b\x42ookService\x12\x41\n\nCreateBook\x12\x1f.library.book.CreateBookRequest\x1a\x12.library.book.Book\x12\x41\n\nUpdateBook\x12\x1f.library.book.UpdateBookRequest\x1a\x12.library.book.Book\x12;\n\x07GetBook\x12\x1c.library.book.GetBookRequest\x1a\x12.library.book.Book\x12R\n\x0bSearchBooks\x12 .library.book.SearchBooksRequest\x1a!.library.book.SearchBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=76
  _globals['_BOOK']._serialized_end=283
  _globals['_CREATEBOOKREQUEST']._serialized_start=285
  _globals['_CREATEBOOKREQUEST']._serialized_end=371
  _globals['_UPDATEBOOKREQUEST']._serialized_start=373
  _globals['_UPDATEBOOKREQUEST']._serialized_end=471
  _globals['_GETBOOKREQUEST']._serialized_start=473
  _globals['_GETBOOKREQUEST']._serialized_end=501
  _globals['_SEARCHBOOKSREQUEST']._serialized_start=503
  _globals['_SEARCHBOOKSREQUEST']._serialized_end=586
  _globals['_SEARCHBOOKSRESPONSE']._serialized_start=588
  _globals['_SEARCHBOOKSRESPONSE']._serialized_end=644
  _globals['_BOOKSERVICE']._serialized_start=647
  _globals['_BOOKSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
