# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import loan_pb2 as loan__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in loan_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoanServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Borrow = channel.unary_unary(
                '/library.loan.LoanService/Borrow',
                request_serializer=loan__pb2.BorrowRequest.SerializeToString,
                response_deserializer=loan__pb2.Loan.FromString,
                _registered_method=True)
        self.ReturnLoan = channel.unary_unary(
                '/library.loan.LoanService/ReturnLoan',
                request_serializer=loan__pb2.ReturnLoanRequest.SerializeToString,
                response_deserializer=loan__pb2.Loan.FromString,
                _registered_method=True)
        self.ListLoans = channel.unary_unary(
                '/library.loan.LoanService/ListLoans',
                request_serializer=loan__pb2.ListLoansRequest.SerializeToString,
                response_deserializer=loan__pb2.ListLoansResponse.FromString,
                _registered_method=True)
        self.ListLoansByMember = channel.unary_unary(
                '/library.loan.LoanService/ListLoansByMember',
                request_serializer=loan__pb2.ListLoansByMemberRequest.SerializeToString,
                response_deserializer=loan__pb2.ListLoansResponse.FromString,
                _registered_method=True)


class LoanServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Borrow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnLoan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLoansByMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoanServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Borrow': grpc.unary_unary_rpc_method_handler(
                    servicer.Borrow,
                    request_deserializer=loan__pb2.BorrowRequest.FromString,
                    response_serializer=loan__pb2.Loan.SerializeToString,
            ),
            'ReturnLoan': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnLoan,
                    request_deserializer=loan__pb2.ReturnLoanRequest.FromString,
                    response_serializer=loan__pb2.Loan.SerializeToString,
            ),
            'ListLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoans,
                    request_deserializer=loan__pb2.ListLoansRequest.FromString,
                    response_serializer=loan__pb2.ListLoansResponse.SerializeToString,
            ),
            'ListLoansByMember': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLoansByMember,
                    request_deserializer=loan__pb2.ListLoansByMemberRequest.FromString,
                    response_serializer=loan__pb2.ListLoansResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.loan.LoanService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.loan.LoanService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoanService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Borrow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.loan.LoanService/Borrow',
            loan__pb2.BorrowRequest.SerializeToString,
            loan__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnLoan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.loan.LoanService/ReturnLoan',
            loan__pb2.ReturnLoanRequest.SerializeToString,
            loan__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.loan.LoanService/ListLoans',
            loan__pb2.ListLoansRequest.SerializeToString,
            loan__pb2.ListLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLoansByMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.loan.LoanService/ListLoansByMember',
            loan__pb2.ListLoansByMemberRequest.SerializeToString,
            loan__pb2.ListLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
