# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: loan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'loan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nloan.proto\x12\x0clibrary.loan\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xd8\x01\n\x04Loan\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x03\x12\x11\n\tmember_id\x18\x03 \x01(\x03\x12/\n\x0b\x62orrowed_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12*\n\x06\x64ue_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0breturned_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nis_overdue\x18\x07 \x01(\x08\"A\n\rBorrowRequest\x12\x0f\n\x07\x62ook_id\x18\x01 \x01(\x03\x12\x11\n\tmember_id\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ys\x18\x03 \x01(\x05\"$\n\x11ReturnLoanRequest\x12\x0f\n\x07loan_id\x18\x01 \x01(\x03\"{\n\x10ListLoansRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x62ook_id\x18\x02 \x01(\x03\x12\x13\n\x0b\x61\x63tive_only\x18\x03 \x01(\x08\x12.\n\npagination\x18\x04 \x01(\x0b\x32\x1a.library.common.Pagination\"-\n\x18ListLoansByMemberRequest\x12\x11\n\tmember_id\x18\x01 \x01(\x03\"6\n\x11ListLoansResponse\x12!\n\x05loans\x18\x01 \x03(\x0b\x32\x12.library.loan.Loan2\xb7\x02\n\x0bLoanService\x12\x39\n\x06\x42orrow\x12\x1b.library.loan.BorrowRequest\x1a\x12.library.loan.Loan\x12\x41\n\nReturnLoan\x12\x1f.library.loan.ReturnLoanRequest\x1a\x12.library.loan.Loan\x12L\n\tListLoans\x12\x1e.library.loan.ListLoansRequest\x1a\x1f.library.loan.ListLoansResponse\x12\\\n\x11ListLoansByMember\x12&.library.loan.ListLoansByMemberRequest\x1a\x1f.library.loan.ListLoansResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'loan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOAN']._serialized_start=76
  _globals['_LOAN']._serialized_end=292
  _globals['_BORROWREQUEST']._serialized_start=294
  _globals['_BORROWREQUEST']._serialized_end=359
  _globals['_RETURNLOANREQUEST']._serialized_start=361
  _globals['_RETURNLOANREQUEST']._serialized_end=397
  _globals['_LISTLOANSREQUEST']._serialized_start=399
  _globals['_LISTLOANSREQUEST']._serialized_end=522
  _globals['_LISTLOANSBYMEMBERREQUEST']._serialized_start=524
  _globals['_LISTLOANSBYMEMBERREQUEST']._serialized_end=569
  _globals['_LISTLOANSRESPONSE']._serialized_start=571
  _globals['_LISTLOANSRESPONSE']._serialized_end=625
  _globals['_LOANSERVICE']._serialized_start=628
  _globals['_LOANSERVICE']._serialized_end=939
# @@protoc_insertion_point(module_scope)
