# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: member.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'member.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmember.proto\x12\x0elibrary.member\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xa5\x01\n\x06Member\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"F\n\x13\x43reateMemberRequest\x12\x11\n\tfull_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\r\n\x05phone\x18\x03 \x01(\t\"R\n\x13UpdateMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05phone\x18\x04 \x01(\t\"\x1e\n\x10GetMemberRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"D\n\x12ListMembersRequest\x12.\n\npagination\x18\x01 \x01(\x0b\x32\x1a.library.common.Pagination\">\n\x13ListMembersResponse\x12\'\n\x07members\x18\x01 \x03(\x0b\x32\x16.library.member.Member2\xc8\x02\n\rMemberService\x12K\n\x0c\x43reateMember\x12#.library.member.CreateMemberRequest\x1a\x16.library.member.Member\x12K\n\x0cUpdateMember\x12#.library.member.UpdateMemberRequest\x1a\x16.library.member.Member\x12\x45\n\tGetMember\x12 .library.member.GetMemberRequest\x1a\x16.library.member.Member\x12V\n\x0bListMembers\x12\".library.member.ListMembersRequest\x1a#.library.member.ListMembersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'member_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBER']._serialized_start=80
  _globals['_MEMBER']._serialized_end=245
  _globals['_CREATEMEMBERREQUEST']._serialized_start=247
  _globals['_CREATEMEMBERREQUEST']._serialized_end=317
  _globals['_UPDATEMEMBERREQUEST']._serialized_start=319
  _globals['_UPDATEMEMBERREQUEST']._serialized_end=401
  _globals['_GETMEMBERREQUEST']._serialized_start=403
  _globals['_GETMEMBERREQUEST']._serialized_end=433
  _globals['_LISTMEMBERSREQUEST']._serialized_start=435
  _globals['_LISTMEMBERSREQUEST']._serialized_end=503
  _globals['_LISTMEMBERSRESPONSE']._serialized_start=505
  _globals['_LISTMEMBERSRESPONSE']._serialized_end=567
  _globals['_MEMBERSERVICE']._serialized_start=570
  _globals['_MEMBERSERVICE']._serialized_end=898
# @@protoc_insertion_point(module_scope)
